name: My Workflow

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build
        run: echo "Building application..."

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Test
        run: echo "Running tests..."

  lint:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: lint
      - run: echo "Lint"

  deploy:
    needs: 
      - test
      - lint
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        run: echo "Deployin applicatio..." 